services:
  mongodb:
    container_name: mongodb
    volumes:
      - mongodb:/data/db

  catalogue:
    container_name: catalogue
    depends_on:
      - mongodb

  # redis:
  #   container_name: redis
  #   volumes:
  #     - redis:/data

  mysql:
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  # rabbitmq:
  #   container_name: rabbitmq
  #   volumes:
  #     - rabbitmq:/var/lib/rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: roboshop
  #     RABBITMQ_DEFAULT_PASS: roboshop123

  user:
    container_name: user
    depends_on:
      - mongodb
      - redis

  cart:
    container_name: cart
    depends_on:
      - redis
      - catalogue

  shipping: 
    container_name: shipping
    depends_on:
      - mysql
      - cart 

  payment: 
    container_name: payment
    depends_on:
      - catalogue
      - user
      - cart

  frontend:
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

volumes:
  mongodb:
  mysql:
  redis:
  rabbitmq:

networks:
  default:
    driver: bridge
    name: roboshop
    external: false
